[build]
  base = "web/"
  command = "yarn export"
  publish = "build/"
  functions = "functions/"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/api/*"
  to = "/404.html"
  status = 404